apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: ts4udocker/ecommerce-rmq_gateway
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: '3000'
            - name: RMQ_URL
              value: amqp://guest:guest@ecommerce-rabbitmq:5672